### PR TITLE
Use Balances API rather than BalanceByAddress

### PR DESCRIPTION
**Pull request by zbuc**
This updates the TypeScript code to be in line with the changes introduced in https://github.com/penumbra-zone/penumbra/pull/2799 to fix compilation errors.

### CODE REVIEW

**Review by aubrika — APPROVED** [review]
LGTM!
